/*
 * Copyright (C) 2024 MDK-Predator Team
 *
 * This file is part of PortaPack.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */

#include "ui.hpp"
#include "mdk_predator_app.hpp"
#include "ui_navigation.hpp"
#include "external_app.hpp"

// Ensure compatibility when building outside the firmware tree or when
// the firmware headers haven't defined these macros yet. The Mayhem
// firmware currently uses header version 0x00000003 for external apps.
#ifndef CURRENT_HEADER_VERSION
#define CURRENT_HEADER_VERSION 0x00000003
#endif

#ifndef VERSION_MD5
// VERSION_MD5 is normally generated by the firmware build system. Use 0
// as a safe default so the app still compiles and the firmware can decide
// whether it accepts the app based on header_version/app_version rules.
#define VERSION_MD5 0x00000000
#endif

namespace ui::external_app::mdk_predator {
void initialize_app(ui::NavigationView& nav) {
    nav.push<MDKPredatorView>();
}
}  // namespace ui::external_app::mdk_predator

extern "C" {

__attribute__((section(".external_app.app_mdk_predator.application_information"), used)) application_information_t _application_information_mdk_predator = {
    /*.memory_location = */ (uint8_t*)0x00000000,
    /*.externalAppEntry = */ ui::external_app::mdk_predator::initialize_app,
    /*.header_version = */ CURRENT_HEADER_VERSION,
    /*.app_version = */ VERSION_MD5,

    /*.app_name = */ "MDK-Predator",
    /*.bitmap_data = */ {
        0x00,
        0x00,
        0xFC,
        0x3F,
        0x04,
        0x20,
        0xE4,
        0x27,
        0x24,
        0x24,
        0x24,
        0x24,
        0xE4,
        0x27,
        0x04,
        0x20,
        0x04,
        0x20,
        0xE4,
        0x27,
        0x24,
        0x24,
        0x24,
        0x24,
        0xE4,
        0x27,
        0x04,
        0x20,
        0xFC,
        0x3F,
        0x00,
        0x00,
    },
    /*.icon_color = */ ui::Color::red().v,
    /*.menu_location = */ app_location_t::UTILITIES,
    /*.desired_menu_position = */ -1,

    /*.m4_app_tag = */ {'P', 'M', 'D', 'P'},
    /*.m4_app_offset = */ 0x00000000,  // will be filled at compile time
};
}
